# Generated by Django 4.2.16 on 2024-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_now', '0002_alter_appointment_user_bookappointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(choices=[('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '01:00 PM'), ('14:00', '02:00 PM'), ('15:00', '03:00 PM'), ('16:00', '04:00 PM'), ('17:00', '05:00 PM'), ('18:00', '06:00 PM'), ('19:00', '07:00 PM'), ('20:00', '08:00 PM')], max_length=5),
        ),
        migrations.DeleteModel(
            name='BookAppointment',
        ),
    ]
