# Generated by Django 4.2.16 on 2024-12-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_now', '0003_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='requests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
