# Generated by Django 4.2.16 on 2024-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=200)),
                ('treatment_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
