# Generated by Django 4.2.16 on 2024-11-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='treatment',
            table='treatments_treatment',
        ),
    ]
