# Generated by Django 4.2.16 on 2024-11-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_treatment_table'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE treatments_post RENAME TO treatments_treatment;"
        ),
    ]
